-- Migrasi 002: Data awal daftar saham IDX LQ45 + beberapa saham populer
-- Jalankan setelah 001_initial_schema.sql.
-- Kode saham tanpa suffix .JK; suffix ditambahkan oleh Data_Fetcher saat memanggil yfinance.

INSERT INTO stocks (kode_saham, nama_perusahaan, aktif) VALUES
    ('AALI', 'Astra Agro Lestari Tbk', TRUE),
    ('ADRO', 'Adaro Energy Indonesia Tbk', TRUE),
    ('AKRA', 'AKR Corporindo Tbk', TRUE),
    ('AMRT', 'Sumber Alfaria Trijaya Tbk', TRUE),
    ('ANTM', 'Aneka Tambang Tbk', TRUE),
    ('ASII', 'Astra International Tbk', TRUE),
    ('BBCA', 'Bank Central Asia Tbk', TRUE),
    ('BBNI', 'Bank Negara Indonesia Tbk', TRUE),
    ('BBRI', 'Bank Rakyat Indonesia Tbk', TRUE),
    ('BBTN', 'Bank Tabungan Negara Tbk', TRUE),
    ('BFIN', 'BFI Finance Indonesia Tbk', TRUE),
    ('BMRI', 'Bank Mandiri Tbk', TRUE),
    ('BRIS', 'Bank Syariah Indonesia Tbk', TRUE),
    ('BRPT', 'Barito Pacific Tbk', TRUE),
    ('BUKA', 'Bukalapak.com Tbk', TRUE),
    ('CPIN', 'Charoen Pokphand Indonesia Tbk', TRUE),
    ('EMTK', 'Elang Mahkota Teknologi Tbk', TRUE),
    ('ERAA', 'Erajaya Swasembada Tbk', TRUE),
    ('EXCL', 'XL Axiata Tbk', TRUE),
    ('GGRM', 'Gudang Garam Tbk', TRUE),
    ('GOTO', 'GoTo Gojek Tokopedia Tbk', TRUE),
    ('HMSP', 'HM Sampoerna Tbk', TRUE),
    ('HRUM', 'Harum Energy Tbk', TRUE),
    ('ICBP', 'Indofood CBP Sukses Makmur Tbk', TRUE),
    ('INCO', 'Vale Indonesia Tbk', TRUE),
    ('INDF', 'Indofood Sukses Makmur Tbk', TRUE),
    ('INKP', 'Indah Kiat Pulp and Paper Tbk', TRUE),
    ('INTP', 'Indocement Tunggal Prakarsa Tbk', TRUE),
    ('ISAT', 'Indosat Tbk', TRUE),
    ('ITMG', 'Indo Tambangraya Megah Tbk', TRUE),
    ('JPFA', 'Japfa Comfeed Indonesia Tbk', TRUE),
    ('JSMR', 'Jasa Marga Tbk', TRUE),
    ('KLBF', 'Kalbe Farma Tbk', TRUE),
    ('MAPI', 'Mitra Adiperkasa Tbk', TRUE),
    ('MBMA', 'Merdeka Battery Materials Tbk', TRUE),
    ('MDKA', 'Merdeka Copper Gold Tbk', TRUE),
    ('MEDC', 'Medco Energi Internasional Tbk', TRUE),
    ('MIKA', 'Mitra Keluarga Karyasehat Tbk', TRUE),
    ('MNCN', 'Media Nusantara Citra Tbk', TRUE),
    ('PGAS', 'Perusahaan Gas Negara Tbk', TRUE),
    ('PGEO', 'Pertamina Geothermal Energy Tbk', TRUE),
    ('PTBA', 'Bukit Asam Tbk', TRUE),
    ('PTPP', 'PP Tbk', TRUE),
    ('SIDO', 'Industri Jamu dan Farmasi Sido Muncul Tbk', TRUE),
    ('SMGR', 'Semen Indonesia Tbk', TRUE),
    ('SMRA', 'Summarecon Agung Tbk', TRUE),
    ('SRTG', 'Saratoga Investama Sedaya Tbk', TRUE),
    ('TINS', 'Timah Tbk', TRUE),
    ('TLKM', 'Telkom Indonesia Tbk', TRUE),
    ('TOWR', 'Sarana Menara Nusantara Tbk', TRUE),
    ('TPIA', 'Chandra Asri Pacific Tbk', TRUE),
    ('UNTR', 'United Tractors Tbk', TRUE),
    ('UNVR', 'Unilever Indonesia Tbk', TRUE),
    ('WIFI', 'Solusi Sinergi Digital Tbk', TRUE),
    ('WSKT', 'Waskita Karya Tbk', TRUE)
ON CONFLICT (kode_saham) DO UPDATE
    SET nama_perusahaan = EXCLUDED.nama_perusahaan,
        updated_at      = NOW();
